[package]
name = "datastore"
version = "0.1.0"
authors = ["Vincent Ambo <tazjin@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
base64 = "0.7.0"
maplit = "0.1.5"

[dependencies.chrono]
version = "0.4.0"
features = ["serde"]
